### ISSUE TITLE
zhihu-server todo

### ISSUE THREAD

**Issue by 0lvpiche0** [WangYifan321/software-process-managment#1]
# 要做的任务
- [x] 完成部署工具和环境的设置
- [x] #3
- [x] 项目config配置
- [x] 完成pojo层接口
- [x] redis接口配置
- [x] 完成Service层接口
- [x] 完成controller层
- [x] 测试

**Comment by mmzkyl** [comment]
config已完成

**Comment by mmzkyl** [comment]
controller已完成

**Comment by mmzkyl** [comment]
dao已完成
